apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpd
  namespace: httpd
spec:
  secretName: httpd
  issuerRef:
    name: private-ca-issuer 
    kind: ClusterIssuer
  dnsNames:
    - httpd.cm.private.nirmata.co
