apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: private-ca-issuer
  namespace: cert-manager
spec:
  acme:
    email: anudeep.nalla@nirmata.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: private-ca-issuer-secret-tls
