apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: zone-service-high-priority
value: 1000000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "Mission Critical apps."

