apiVersion: v1
data:
  defaultRegistry: docker.io
  enableDefaultRegistryMutation: "true"
  excludeGroups: system:nodes
  generateSuccessEvents: "false"
  resourceFilters: '[*/*,default,*] [Event,*,*] [*/*,kube-system,*] [*/*,kube-public,*]
    [*/*,kube-node-lease,*] [Node,*,*] [Node/*,*,*] [APIService,*,*] [APIService/*,*,*]
    [TokenReview,*,*] [SubjectAccessReview,*,*] [SelfSubjectAccessReview,*,*] [Binding,*,*]
    [Pod/binding,*,*] [ReplicaSet,*,*] [ReplicaSet/*,*,*] [AdmissionReport,*,*] [AdmissionReport/*,*,*]
    [ClusterAdmissionReport,*,*] [ClusterAdmissionReport/*,*,*] [BackgroundScanReport,*,*]
    [BackgroundScanReport/*,*,*] [ClusterBackgroundScanReport,*,*] [ClusterBackgroundScanReport/*,*,*]
    [ClusterRole,*,release-name-kyverno:admission-controller] [ClusterRole,*,release-name-kyverno:admission-controller:core]
    [ClusterRole,*,release-name-kyverno:admission-controller:additional] [ClusterRole,*,release-name-kyverno:background-controller]
    [ClusterRole,*,release-name-kyverno:background-controller:core] [ClusterRole,*,release-name-kyverno:background-controller:additional]
    [ClusterRole,*,release-name-kyverno:cleanup-controller] [ClusterRole,*,release-name-kyverno:cleanup-controller:core]
    [ClusterRole,*,release-name-kyverno:cleanup-controller:additional] [ClusterRole,*,release-name-kyverno:reports-controller]
    [ClusterRole,*,release-name-kyverno:reports-controller:core] [ClusterRole,*,release-name-kyverno:reports-controller:additional]
    [ClusterRoleBinding,*,release-name-kyverno:admission-controller] [ClusterRoleBinding,*,release-name-kyverno:background-controller]
    [ClusterRoleBinding,*,release-name-kyverno:cleanup-controller] [ClusterRoleBinding,*,release-name-kyverno:reports-controller]
    [ServiceAccount,default,kyverno-admission-controller] [ServiceAccount/*,default,kyverno-admission-controller]
    [ServiceAccount,default,kyverno-background-controller] [ServiceAccount/*,default,kyverno-background-controller]
    [ServiceAccount,default,kyverno-cleanup-controller] [ServiceAccount/*,default,kyverno-cleanup-controller]
    [ServiceAccount,default,kyverno-reports-controller] [ServiceAccount/*,default,kyverno-reports-controller]
    [Role,default,release-name-kyverno:admission-controller] [Role,default,release-name-kyverno:background-controller]
    [Role,default,release-name-kyverno:cleanup-controller] [Role,default,release-name-kyverno:reports-controller]
    [RoleBinding,default,release-name-kyverno:admission-controller] [RoleBinding,default,release-name-kyverno:background-controller]
    [RoleBinding,default,release-name-kyverno:cleanup-controller] [RoleBinding,default,release-name-kyverno:reports-controller]
    [ConfigMap,default,release-name-kyverno] [ConfigMap,default,release-name-kyverno-metrics]
    [Deployment,default,kyverno-admission-controller] [Deployment/*,default,kyverno-admission-controller]
    [Deployment,default,kyverno-background-controller] [Deployment/*,default,kyverno-background-controller]
    [Deployment,default,kyverno-cleanup-controller] [Deployment/*,default,kyverno-cleanup-controller]
    [Deployment,default,kyverno-reports-controller] [Deployment/*,default,kyverno-reports-controller]
    [Pod,default,kyverno-admission-controller-*] [Pod/*,default,kyverno-admission-controller-*]
    [Pod,default,kyverno-background-controller-*] [Pod/*,default,kyverno-background-controller-*]
    [Pod,default,kyverno-cleanup-controller-*] [Pod/*,default,kyverno-cleanup-controller-*]
    [Pod,default,kyverno-reports-controller-*] [Pod/*,default,kyverno-reports-controller-*]
    [Job,default,release-name-kyverno-hook-pre-delete] [Job/*,default,release-name-kyverno-hook-pre-delete]
    [NetworkPolicy,default,kyverno-admission-controller] [NetworkPolicy/*,default,kyverno-admission-controller]
    [NetworkPolicy,default,kyverno-background-controller] [NetworkPolicy/*,default,kyverno-background-controller]
    [NetworkPolicy,default,kyverno-cleanup-controller] [NetworkPolicy/*,default,kyverno-cleanup-controller]
    [NetworkPolicy,default,kyverno-reports-controller] [NetworkPolicy/*,default,kyverno-reports-controller]
    [PodDisruptionBudget,default,kyverno-admission-controller] [PodDisruptionBudget/*,default,kyverno-admission-controller]
    [PodDisruptionBudget,default,kyverno-background-controller] [PodDisruptionBudget/*,default,kyverno-background-controller]
    [PodDisruptionBudget,default,kyverno-cleanup-controller] [PodDisruptionBudget/*,default,kyverno-cleanup-controller]
    [PodDisruptionBudget,default,kyverno-reports-controller] [PodDisruptionBudget/*,default,kyverno-reports-controller]
    [Service,default,release-name-kyverno-svc] [Service/*,default,release-name-kyverno-svc]
    [Service,default,release-name-kyverno-svc-metrics] [Service/*,default,release-name-kyverno-svc-metrics]
    [Service,default,kyverno-background-controller-metrics] [Service/*,default,kyverno-background-controller-metrics]
    [Service,default,kyverno-cleanup-controller] [Service/*,default,kyverno-cleanup-controller]
    [Service,default,kyverno-cleanup-controller-metrics] [Service/*,default,kyverno-cleanup-controller-metrics]
    [Service,default,kyverno-reports-controller-metrics] [Service/*,default,kyverno-reports-controller-metrics]
    [ServiceMonitor,default,kyverno-admission-controller] [ServiceMonitor,default,kyverno-background-controller]
    [ServiceMonitor,default,kyverno-cleanup-controller] [ServiceMonitor,default,kyverno-reports-controller]
    [Secret,default,release-name-kyverno-svc.default.svc.*] [Secret,default,kyverno-cleanup-controller.default.svc.*]'
  webhooks: '[{"namespaceSelector":{"matchExpressions":[{"key":"kubernetes.io/metadata.name","operator":"NotIn","values":["kube-system","kube-public","zone-policy-manager","calico-apiserver","calico-system","istio-system","istio-operator","tigera-operator","zone-secops","atlantis","olympus-cluster-provisioner","zone-auth","zone-fe-infra","zone-infra","zone-logging","zone-monitoring","zone-tracing","zone-traffic","zone-vault"]},{"key":"kubernetes.io/metadata.name","operator":"NotIn","values":["default"]}],"matchLabels":null}}]'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: release-name-kyverno
    app.kubernetes.io/version: 3.0.8
    helm.sh/chart: kyverno-3.0.8
  name: release-name-kyverno
  namespace: zone-policy-manager
