apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: splunk-operator-test
    meta.helm.sh/release-namespace: splunk-operator
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: splunk-operator-test
    app.kubernetes.io/managed-by: Helm
  name: splunk-operator-app-download
  namespace: splunk-operator
spec:
  storageClassName: nirmata-hostpath      
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
