apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2023-11-24T07:55:27Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: standalone
    app.kubernetes.io/instance: splunk-s1-standalone
    app.kubernetes.io/managed-by: splunk-operator
    app.kubernetes.io/name: standalone
    app.kubernetes.io/part-of: splunk-s1-standalone
  name: pvc-etc-splunk-s1-standalone-0
  namespace: splunk-operator
spec:
  storageClassName: nirmata-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
