apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2023-11-24T09:22:01Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    name: splunk-operator
  name: splunk-operator-app-download
  namespace: splunk-operator
spec:
  storageClassName: nirmata-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
