apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-volume-types-dev-9
  annotations:
    policies.kyverno.io/title: Restrict Volume Types
    policies.kyverno.io/description: >-
      In addition to restricting HostPath volumes, the restricted pod security profile
      limits usage of non-core volume types to those defined through PersistentVolumes.
      This policy blocks any other type of volume other than those in the allow list.
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: restricted-volumes-9
      exclude:
        any:
        - resources:
            kinds:
              - Pod
            selector:
              matchExpressions:
                - key: environment.tess.io/name
                  operator: In
                  values:
                  - dev
                  - feature
                  - lnp
                  - staging
                  - stagingpci
                  - stagingrnpci
                - key: application.tess.io/name
                  operator: In
                  values:
                  - tfap-lnp
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - tfap-lnp
            selector:
              matchExpressions:
                - key: environment.tess.io/name
                  operator: In
                  values:
                  - dev
                  - feature
                  - lnp
                  - staging
                  - stagingpci
                  - stagingrnpci
      validate:
        message: >-
          Only the following types of volumes may be used: configMap, csi, downwardAPI,
          emptyDir, ephemeral, persistentVolumeClaim, projected, and secret.
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.volumes[].keys(@)[] || '' }}"
              operator: AnyNotIn
              value:
              - flexVolume
              - emptyDir
              - secret
              - nfs
              - iscsi
              - persistentVolumeClaim
              - rbd
              - cinder
              - cephFS
              - downwardAPI
              - configMap
              - csi
              - projected
              - ''